### ISSUE TITLE
Fix all dead links 

### ISSUE THREAD

**Issue by FlorianFranzen** [w3f/research#100]
I keep finding dead links on the research page, so I ran a quick link check and collected all the issues I found here.

First of is a dead link to a slashing page that does not exist.

URL        `slashing'
Name       `Slashing mechanism'
Parent URL https://w3f-research.readthedocs.io/en/latest/polkadot/index.html, line 474, col 207
Real URL   https://w3f-research.readthedocs.io/en/latest/polkadot/slashing

The other issues all broken links to member profiles, caused by the fact that read the docs hosts the latest version of the research page under `en/latest/`.

URL        `/research_team_members/syed.html'
Name       `Syed Hosseini'
Parent URL https://w3f-research.readthedocs.io/en/latest/polkadot/Polkadot-Host-Spec.html, line 324, col 29
Real URL   https://w3f-research.readthedocs.io/research_team_members/syed.html

URL        `/research_team_members/alistair.html'
Name       `Alistair Stewart'
Parent URL https://w3f-research.readthedocs.io/en/latest/polkadot/finality.html, line 392, col 11
Real URL   https://w3f-research.readthedocs.io/research_team_members/alistair.html

URL        `/research_team_members/jeff.html'
Name       `Jeff Burdges'
Parent URL https://w3f-research.readthedocs.io/en/latest/polkadot/Availability_and_Validity.html, line 360, col 29
Real URL   https://w3f-research.readthedocs.io/research_team_members/jeff.html

URL        `/research_team_members/Ximin.html'
Name       `Ximin Luo'
Parent URL https://w3f-research.readthedocs.io/en/latest/polkadot/networking/0-overview.html, line 457, col 29
Real URL   https://w3f-research.readthedocs.io/research_team_members/Ximin.html

URL        `/research_team_members/alfonso.html'
Name       `Alfonso Cevallos'
Parent URL https://w3f-research.readthedocs.io/en/latest/polkadot/Token%20Economics.html, line 497, col 29
Real URL   https://w3f-research.readthedocs.io/research_team_members/alfonso.html

URL        `/research_team_members/Jonas.html'
Name       `Jonas Gehrlein'
Parent URL https://w3f-research.readthedocs.io/en/latest/polkadot/Token%20Economics.html, line 497, col 124
Real URL   https://w3f-research.readthedocs.io/research_team_members/Jonas.html

URL        `/research_team_members/handan.html'
Name       `Handan Kilinc Alper'
Parent URL https://w3f-research.readthedocs.io/en/latest/polkadot/block-production/Babe.html, line 596, col 29
Real URL   https://w3f-research.readthedocs.io/research_team_members/handan.html

**Comment by infinity0** [comment]
@FlorianFranzen the CI performs some link checks, which is how I found some previous ones. Do you know why it didn't catch these?

**Comment by infinity0** [comment]
I can fix these, though.

**Comment by infinity0** [comment]
@FlorianFranzen oh, the real reason is because our readthedocs configuration is broken - you need to tell sphinx that the website base is /en/latest not /.

**Comment by infinity0** [comment]
Nvmd, it is broken everywhere, I will fix that.

**Comment by infinity0** [comment]
The reason the CI link checker is not finding these broken links, is probably because it is configured to check the documents under / and not /en/latest.

**Comment by infinity0** [comment]
Links are fixed, I will file another bug for the CI.
