### ISSUE TITLE
The LaTeX rendering does not work in XCMP networking page

### ISSUE THREAD

**Issue by IkerAlus** [w3f/research#131]
The version at https://research.web3.foundation/ of the XCMP networking page ([link](
https://research.web3.foundation/en/latest/polkadot/networking/4-xcmp.html)) is not rendering the LaTex syntax correctly. This issue is not present if I access this page from the GitHub repo.

**Comment by AlistairStewart** [comment]
There is no such page now, which is sensible as we will likely use a very different approach.
