### ISSUE TITLE
Update the writeup about keys

### ISSUE THREAD

**Issue by keorn** [w3f/research#3]

**Comment by burdges** [comment]
I've done this now.  We should eventually homogenize with the write up by gavin and the code of course. 
 - https://github.com/paritytech/substrate/pull/1782#discussion_r260265815 
 - https://github.com/paritytech/substrate/blob/1a2ec9eec1fe9b3cc2677bac629fd7e9b0f6cf8e/srml/staking/Staking.md aka https://github.com/paritytech/substrate/commit/1a2ec9eec1fe9b3cc2677bac629fd7e9b0f6cf8e

In particular, I proposed an unstaking scheme by partially describing the state transition associated to the account, but it's permits large account data structures, so maybe another design works better.

Also, it now addresses Gavin's question about multiple account key types, with the recommendation being that each account support only one key type.
