### ISSUE TITLE
The section about secio is obsolete

### ISSUE THREAD

**Issue by tomaka** [w3f/research#91]
https://github.com/w3f/research/blob/master/docs/polkadot/keys/4-secio.md

The document mentions scepticism about secio, and we've since then removed secio from the Substrate and Polkadot code bases.
Polkadot/Kusama right now are using the official libp2p noise.

The plan to try to use QUIC in the long term is still relevant, though.

@burdges I've been told to ping you!

**Comment by burdges** [comment]
It's maybe more @infinity0 now than me, but I can make some changes.

**Comment by infinity0** [comment]
Didn't realise that section existed but sure, I can take responsibility for fixing this. A large section of the docs are slightly out-of-date for sure and could do with a revamp.

**Comment by burdges** [comment]
It's extremely stale now, so I just removed it in https://github.com/w3f/research/commit/9ffffa052155465a83f938cbddad86b52f78b96a

I've never figured out whether certifying transport layer keys matters much.  I'm still pushing for it as a defense in depth, so presumably anything that goes here should discuss certifying transport layer keys, ala https://github.com/w3f/research-security-issues/issues/25 and https://github.com/paritytech/substrate/pull/6251#issuecomment-641502841 

We should prioritize networking improvements that impact scalability however, so imho this could sit empty for a while.  I'll mention it in https://github.com/w3f/research-security-issues/issues/25
